FileSet {
  Name = "Windows All Drives"
  Enable VSS = yes
  Include {
    Options {
      Signature = XXH128
      Drive Type = fixed
      IgnoreCase = yes
      WildFile = "[A-Z]:/hiberfil.sys"
      WildFile = "[A-Z]:/pagefile.sys"
      WildFile = "[A-Z]:/swapfile.sys"
      WildFile = "[A-Z]:/*Thumbs.db"
      WildDir = "[A-Z]:/RECYCLER"
      WildDir = "[A-Z]:/$RECYCLE.BIN"
      WildDir = "[A-Z]:/System Volume Information"
      WildDir = "[A-Z]:/Windows/SoftwareDistribution/Download"
      WildDir = "[A-Z]:/Windows/Temp"
      WildDir = "[A-Z]:/Windows/Prefetch"
      WildDir = "[A-Z]:/Windows/assembly/temp"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Temp"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Microsoft/Windows/INetCache"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Microsoft/Windows/WebCache"
      WildDir = "[A-Z]:/Users/*/AppData/roaming/Microsoft/Teams/Service Worker/CacheStorage"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Google/Chrome/User Data/Default/Cache"
      WildDir = "[A-Z]:/inetpub/logs"
      WildDir = "[A-Z]:/Windows/System32/LogFiles"
      WildDir = "[A-Z]:/inetpub/temp"
      WildDir = "[A-Z]:/Windows/Logs"
      Exclude = yes
      Compression = lzo
    }
    File = /
  }
}

FileSet {
  Name = "Windows All Drives-atlas"
  Enable VSS = yes
  Include {
    Options {
      Signature = XXH128
      Drive Type = fixed
      IgnoreCase = yes
      WildFile = "[A-Z]:/hiberfil.sys"
      WildFile = "[A-Z]:/pagefile.sys"
      WildFile = "[A-Z]:/swapfile.sys"
      WildFile = "[A-Z]:/*Thumbs.db"
      WildDir = "[A-Z]:/RECYCLER"
      WildDir = "[A-Z]:/$RECYCLE.BIN"
      WildDir = "[A-Z]:/System Volume Information"
      WildDir = "[A-Z]:/Windows/SoftwareDistribution/Download"
      WildDir = "[A-Z]:/Windows/Temp"
      WildDir = "[A-Z]:/Windows/Prefetch"
      WildDir = "[A-Z]:/Windows/assembly/temp"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Temp"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Microsoft/Windows/INetCache"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Microsoft/Windows/WebCache"
      WildDir = "[A-Z]:/Users/*/AppData/roaming/Microsoft/Teams/Service Worker/CacheStorage"
      WildDir = "[A-Z]:/Users/*/AppData/Local/Google/Chrome/User Data/Default/Cache"
      WildDir = "[A-Z]:/inetpub/logs"
      WildDir = "[A-Z]:/Windows/System32/LogFiles"
      WildDir = "[A-Z]:/inetpub/temp"
      WildDir = "[A-Z]:/Windows/Logs"
      Exclude = yes
      Compression = lzo
    }
    File = /
  }
}
