---

- name: install and configure msmtp
  hosts: uptime_kuma
  become: true
  vars:
    srv: msmtp
  tasks:
  - name: install {{ srv }}
    pkgng:
      name: {{ srv }}
  - name: add {{ srv }} runsv directory
    ansible.builtin.file:
      path: "/etc/sv/{{ srv }}"
      state: directory
      mode: '0755'
  - name: add {{ srv }} runsv file
    ansible.builtin.template:
      src: "../../templates/runit/{{ srv }}_run"
      dest: "/etc/sv/{{ srv }}/run"
      owner: root
      group: wheel
      mode: '0755'
  - name: enable {{ srv }} boot
    ansible.builtin.file:
      src: '/etc/sv/{{ srv }}'
      dest: '/var/service/{{ srv }}'
      state: link
