---

- ansible.builtin.import_playbook: playbooks/runit.yml
- ansible.builtin.import_playbook: playbooks/essential_pkgs.yml
- ansible.builtin.import_playbook: playbooks/cron.yml
- ansible.builtin.import_playbook: playbooks/periodic_ansible_pull.yml
- ansible.builtin.import_playbook: playbooks/ntpd.yml
- ansible.builtin.import_playbook: playbooks/samba.yml
- ansible.builtin.import_playbook: playbooks/sshd.yml
- ansible.builtin.import_playbook: playbooks/sssd.yml
- ansible.builtin.import_playbook: playbooks/sudo.yml
