---

- ansible.builtin.import_playbook: playbooks/all/boot_loader_conf.yml
- ansible.builtin.import_playbook: playbooks/all/zfs.yml
- ansible.builtin.import_playbook: playbooks/all/sudo.yml

- ansible.builtin.import_playbook: playbooks/all/keymap.yml
- ansible.builtin.import_playbook: playbooks/all/pkg.yml
- ansible.builtin.import_playbook: playbooks/all/essential_pkgs.yml
- ansible.builtin.import_playbook: playbooks/all/periodic_ansible_pull.yml

- ansible.builtin.import_playbook: playbooks/all/runit.yml
- ansible.builtin.import_playbook: playbooks/all/cron.yml
- ansible.builtin.import_playbook: playbooks/all/devd.yml
- ansible.builtin.import_playbook: playbooks/all/fonts.yml
- ansible.builtin.import_playbook: playbooks/all/ntpd.yml
- ansible.builtin.import_playbook: playbooks/all/samba.yml
- ansible.builtin.import_playbook: playbooks/all/sshd.yml
- ansible.builtin.import_playbook: playbooks/all/sssd.yml
- ansible.builtin.import_playbook: playbooks/all/webfilter_cert.yml

- ansible.builtin.import_playbook: webserver.yml
- ansible.builtin.import_playbook: secure_webserver.yml
- ansible.builtin.import_playbook: workstation.yml
- ansible.builtin.import_playbook: laptop_hp.yml

- ansible.builtin.import_playbook: playbooks/uptime_kuma/uptime_kuma.yml
