---

- ansible.builtin.import_playbook: playbooks/all/pkg.yml
- ansible.builtin.import_playbook: playbooks/all/boot_loader_conf.yml
- ansible.builtin.import_playbook: playbooks/all/zfs.yml
- ansible.builtin.import_playbook: playbooks/all/essential_pkgs.yml
- ansible.builtin.import_playbook: playbooks/all/sudo.yml

- ansible.builtin.import_playbook: playbooks/all/keymap.yml
- ansible.builtin.import_playbook: playbooks/all/periodic_ansible_pull.yml

- ansible.builtin.import_playbook: playbooks/all/runit.yml
- ansible.builtin.import_playbook: playbooks/all/cron.yml
- ansible.builtin.import_playbook: playbooks/all/fonts.yml
- ansible.builtin.import_playbook: playbooks/all/ntpd.yml
- ansible.builtin.import_playbook: playbooks/all/samba.yml
- ansible.builtin.import_playbook: playbooks/all/dbus.yml
- ansible.builtin.import_playbook: playbooks/all/sshd.yml
- ansible.builtin.import_playbook: playbooks/all/sssd.yml
- ansible.builtin.import_playbook: playbooks/all/webfilter_cert.yml
- ansible.builtin.import_playbook: playbooks/all/certmonger.yml
- ansible.builtin.import_playbook: playbooks/all/periodic_reset_machine_password.yml

- ansible.builtin.import_playbook: playbooks/freeradius3/freeradius3.yml
- ansible.builtin.import_playbook: playbooks/jailer/jail.yml
- ansible.builtin.import_playbook: playbooks/servers/full-ca-chain.yml
- ansible.builtin.import_playbook: webserver.yml
- ansible.builtin.import_playbook: secure_webserver.yml
- ansible.builtin.import_playbook: package_builder.yml
- ansible.builtin.import_playbook: workstation.yml
- ansible.builtin.import_playbook: laptop_hp.yml

- ansible.builtin.import_playbook: playbooks/uptime_kuma/uptime_kuma.yml
- ansible.builtin.import_playbook: playbooks/uptime_kuma/msmtp.yml

- ansible.builtin.import_playbook: playbooks/dmarc_report_analyser/dmarc-report-analyser.yml
- ansible.builtin.import_playbook: playbooks/bhyve/bhyve.yml

- ansible.builtin.import_playbook: playbooks/backups/bareos-dir.yml
- ansible.builtin.import_playbook: playbooks/backups/bareos-storage.yml
- ansible.builtin.import_playbook: playbooks/backups/bareos-client.yml
