Job {
  Name = "atlas-diff-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Offsite-diff
  Next Pool = Atlas-diff
  Priority = 1000
}
