Job {
  Name = "atlas-full-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Sneakernet-full
  Next Pool = Atlas
  Priority = 2000
  Enabled = no
}
