Job {
  Name = "atlas-full-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Offsite-full
  Next Pool = Atlas-full
  Priority = 1000
}
