Job {
  Name = "atlas-inc-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Offsite-inc
  Next Pool = Atlas-inc
  Priority = 1000
}
