Job {
  Name = "Consolidate"
  Type = Consolidate
  Client = bareos-fd
  Fileset = Catalog
  Pool = Incremental
  Next Pool = Full
  Max Full Consolidations = 20
  Accurate = yes
  Messages = Standard
  Schedule = "WeeklyCycle"
}
