Job {
  Name = dshs-dc03-image
  Description = "DSHS-DC03 Image backup"
  Type = Backup
  Schedule = "WeeklyCycleAfterBackup"
  Client = dshs-dc03
  JobDefs = DefaultJob
  Fileset = dc03-ImageBackup
  Priority = 11                   # run after main backup

  Run Script {
    Command = "wbadmin.exe start backup -backupTarget:\\\\dshs-backup-j1.dshs.local\\windows-images -include:C: -allCritical -vssCopy -quiet"
    RunsWhen = Before
    RunsOnClient = Yes
  }
}

Fileset {
  Name = dc03-ImageBackup
  Include {
    File = "C:/ProgramData/Bareos/bareos-fd.d"
  }
}
