Job {
  Name = RsyncOffsite
  Description = "Rsync offsite backup"
  Type = Backup
  Schedule = "WeeklyCycleAfterBackup"
  Client = dshs-backup-j1
  JobDefs = DefaultJob
  Fileset = RsyncOffsite
  Priority = 12                   # run after main backup

  Run Script {
    Command = "/bin/sh /usr/local/etc/bareos/rsync_backup.sh -v"
    RunsWhen = After
    RunsOnClient = Yes
  }
}

Fileset {
  Name = RsyncOffsite
  Include {
    File = /nonexistent
  }
}
