Job {
  Name = "sneakernet-inc-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Atlas-diff
  Next Pool = Sneakernet-other
  Priority = 1000
}
