Job {
  Name = "sneakernet-inc-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Incremental
  Next Pool = Sneakernet-other
  Priority = 1000
  Enabled = no
}
