Job {
  Name = "sneakernet-full-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Atlas-full
  Next Pool = Sneakernet-full
  Priority = 1000
}
