Job {
  Name = "sneakernet-full-copy"
  Type = Copy
  Schedule = "WeeklyCycleAfterBackup"
  Messages = Standard
  Selection Type = PoolUncopiedJobs
  Pool = Full
  Next Pool = Sneakernet-full
  Priority = 1000
  Enabled = no
}
