#!/bin/sh

for l in /etc/ssl/private                       \
         /etc/ssl/private/certmonger.key        \
         /usr/local/etc/letsencrypt/live        \
         /etc/ssl/certs/certmonger.crt          \
         /var/db/samba4/winbindd_privileged     \
         /usr/local/etc/letsencrypt/live        \
         ; do
        chgrp freeradius $l
        chmod g+rX $l
done

exec /usr/local/sbin/radiusd -fX
