#!/bin/sh

ping -t 1 $(/bin/hostname) || exit 1

install -d -o dshs-rclone-rclone -g "Domain users" -m 0700 ~dshs-rclone-rclone
install -d -o dshs-rclone-rclone -g "Domain users" -m 0700 ~dshs-rclone-rclone/sharepoint_all

kldload -n fusefs

exec chpst -u dshs-rclone-rclone rclone --config ~dshs-rclone-rclone/.config/rclone/rclone.conf mount --read-only all: ~dshs-rclone-rclone/sharepoint_all
