Autochanger {
  Name = FileStorage
  Device = FileStorage-0
  Device = FileStorage-1
  Changer Command = ""
  Changer Device = /dev/null
}

Device {
  Name = FileStorage-0
  Drive Index = 0
  Media Type = File
  Archive Device = /bareos-storage
  LabelMedia = yes;                   # lets Bareos label unlabeled media
  Random Access = yes;
  AutomaticMount = yes;               # when device opened, read it
  RemovableMedia = no;
  AlwaysOpen = no;
  AutoChanger = yes
  Description = "File device. A connecting Director must have the same Name and MediaType."
  Auto Inflate = In
}
Device {
  Name = FileStorage-1
  Drive Index = 1
  Media Type = File
  Archive Device = /bareos-storage
  LabelMedia = yes;                   # lets Bareos label unlabeled media
  Random Access = yes;
  AutomaticMount = yes;               # when device opened, read it
  RemovableMedia = no;
  AlwaysOpen = no;
  AutoChanger = yes
  Description = "File device. A connecting Director must have the same Name and MediaType."
  Auto Inflate = In
}
