JobDefs {
  Name = "UNIX-zfs-vss"
  Type = Backup
  Level = Incremental
  Client = bareos-fd
  Accurate = yes
  FileSet = "UNIX-zfs-vss"                     # selftest fileset
  Schedule = "WeeklyCycle-AI"
  Client Run Before Job = "/bin/sh /root/scripts/zfs_vss.sh"
  Run Script {
    Runs When = After
    Runs On Client = yes
    Runs On Success = yes
    Runs On Failure = yes
    Command = "/bin/sh /root/scripts/zfs_vss.sh -r"
  }
  Messages = Standard
  Pool = Full                              # default
  Full Backup Pool = Full                  # write Full Backups into "Full" Pool
  Incremental Backup Pool = Incremental    # write Incr Backups into "Incremental" Pool
  Always Incremental = yes
  Always Incremental Keep Number = 14 days
  Always Incremental Job Retention = 14 days
  Priority = 10
  Write Bootstrap = "/var/db/bareos/%c.bsr"
}

JobDefs {
  Name = "UNIX-zfs-vss-offsite"
  Type = Backup
  Level = Incremental
  Client = bareos-fd
  Accurate = yes
  FileSet = "UNIX-zfs-vss-offsite"                     # selftest fileset
  Schedule = "WeeklyCycle"
  Client Run Before Job = "/bin/sh /root/scripts/zfs_vss.sh"
  Run Script {
    Runs When = After
    Runs On Client = yes
    Runs On Success = yes
    Runs On Failure = yes
    Command = "/bin/sh /root/scripts/zfs_vss.sh -r"
  }
  Messages = Standard
  Pool = Offsite-full                              # default
  Full Backup Pool = Offsite-full                  # write Full Backups into "Full" Pool
  Differential Backup Pool = Offsite-diff  # write Diff Backups into "Differential" Pool
  Incremental Backup Pool = Offsite-inc    # write Incr Backups into "Incremental" Pool
  Priority = 10
  Write Bootstrap = "/var/db/bareos/%c.bsr"
}
