JobDefs {
  Name = "Windows"
  Type = Backup
  Level = Incremental
  Client = bareos-fd
  Accurate = yes
  FileSet = "Windows All Drives"                     # selftest fileset
  Schedule = "WeeklyCycle"
  Messages = Standard
  Pool = Full                              # default
  Full Backup Pool = Full                  # write Full Backups into "Full" Pool
  Differential Backup Pool = Differential  # write Diff Backups into "Differential" Pool
  Incremental Backup Pool = Incremental    # write Incr Backups into "Incremental" Pool
  Always Incremental = yes
  Always Incremental Keep Number = 14
  Priority = 10
  Write Bootstrap = "/var/db/bareos/%c.bsr"
}

JobDefs {
  Name = "Windows-atlas"
  Type = Backup
  Level = Incremental
  Client = bareos-fd
  Accurate = yes
  FileSet = "Windows All Drives-atlas"                     # selftest fileset
  Schedule = "WeeklyCycle"
  Messages = Standard
  Pool = Atlas-full                              # default
  Full Backup Pool = Atlas-full                  # write Full Backups into "Full" Pool
  Differential Backup Pool = Atlas-diff  # write Diff Backups into "Differential" Pool
  Incremental Backup Pool = Atlas-inc    # write Incr Backups into "Incremental" Pool
  Priority = 10
  Write Bootstrap = "/var/db/bareos/%c.bsr"
}
