---

- name: install and activate poudriere
  hosts: package_builder
  become: true
  tasks:
  - name: install poudriere
    pkgng:
      name: poudriere ccache
  - name: configure poudriere
    ansible.builtin.template:
      src: ../../templates/poudriere/poudriere.conf
      dest: /usr/local/etc/poudriere.conf
      owner: root
      group: wheel
      mode: '0644'
  - name: make sure filesystems are created
    ansible.builtin.command:
      cmd: /usr/local/bin/poudriere jail -l
      creates: /poudriere
  - name: create directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    loop:
      - /poudriere/data/packages
      - /poudriere/data/scripts
      - /poudriere/data/src
      - /poudriere/pkgbase_repo
      - /var/cache/ccache
  - name: copy script for periodic running
    ansible.builtin.template:
      src: "../../templates/poudriere/{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: wheel
      mode: '0755'
    loop:
      - { src: base_pkg_build.sh, dest: /poudriere/data/scripts/base_pkg_build.sh }
      - { src: poudriere.d/make.conf, dest: /usr/local/etc/poudriere.d/make.conf }
      - { src: poudriere_cron, dest: /etc/cron.d/poudriere }
      - { src: poudriere.d/pkglist-dshs, dest: /usr/local/etc/poudriere.d/pkglist-dshs }
      - { src: poudriere.d/pkglist-dshs-mailserver, dest: /usr/local/etc/poudriere.d/pkglist-dshs-mailserver }
      - { src: poudriere.d/pkglist-dshs-netbox, dest: /usr/local/etc/poudriere.d/pkglist-dshs-netbox }
      - { src: poudriere.d/pkglist-dshs-webserver, dest: /usr/local/etc/poudriere.d/pkglist-dshs-webserver }
      - { src: poudriere.d/pkglist-dshs-workstation, dest: /usr/local/etc/poudriere.d/pkglist-dshs-workstation }
      - { src: poudriere.d/pkglist-dshs-workstation-extras, dest: /usr/local/etc/poudriere.d/pkglist-dshs-workstation-extras }
      - { src: poudriere.d/pkglist-dshs-workstation-laptop-hp, dest: /usr/local/etc/poudriere.d/pkglist-dshs-workstation-laptop-hp }
      - { src: poudriere.d/pkglist-dshs-dmarc-report-analyser, dest: /usr/local/etc/poudriere.d/pkglist-dshs-dmarc-report-analyser }
  - name: add links for packages for webserver
    ansible.builtin.file:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
      state: link
    loop:
      - { src: /poudriere/data/packages, dest: /usr/local/www/apache24/data/pkg }
      - { src: /poudriere/pkgbase_repo, dest: /usr/local/www/apache24/data/pkgbase }
      - { src: /poudriere/data/logs/bulk, dest: /usr/local/www/apache24/data/poudriere }
