---

- name: enable dmarcts_analyser
  hosts: dshs-leibniz.dshs.local
  become: true
  vars:
    n: dmarc
    homedir: /var/db/dmarc
  tasks:
  - name: install dmarcts analyser
    community.general.pkgng:
      name:
        - dmarcts-report-parser
        - p5-DBD-mysql
        - mail/getmail6
        - databases/php83-pdo_mysql
    register: installed
  - name: make dmarcts_analyser conf file unreadable
    ansible.builtin.file:
      path: /usr/local/etc/dmarcts-report-parser.conf
      mode: '0600'
  - name: 'make sure {{ n }} user exists'
    ansible.builtin.user:
      name: '{{ n }}'
      comment: '& user'
      group: daemon
      password: '*'
      shell: /bin/sh
      home: '{{ homedir }}'
  - name: get report analyser
    ansible.builtin.git:
      repo: 'https://github.com/techsneeze/dmarcts-report-viewer'
      dest: /usr/local/www/apache24/data/dmarc
    when: installed.changed is true
  - name: add periodic scripts
    ansible.builtin.template:
      src: '../../templates/periodic/daily/{{ item }}'
      dest: '/usr/local/etc/periodic/daily/{{ item }}'
      owner: root
      group: wheel
      mode: '0755'
    loop:
      - 150.dmarc_getmail
      - 160.dmarcts-report-parser-dshs
  - name: enable periodic jobs
    community.general.sysrc:
      path: /etc/periodic.conf
      name: '{{ item }}_enable'
      value: yes
    loop:
      - daily_dmarcts_report_parser_dshs
      - daily_dmarc_getmail
