---

- name: set graphics driver
  hosts: workstation
  become: true
  tasks:
  - name: install drm kmod
    community.general.pkgng:
      name: drm-61-kmod
  - name: enable i915kms
    community.general.sysrc:
      name: kld_list
      value: "i915kms"
