---

- name: enable webcamd
  hosts: workstation
  become: true
  tasks:
  - name: enable webcamd rc.conf
    community.general.sysrc:
      name: 'webcamd_{{ item.option }}'
      value: "{{ item.value }}"
    loop:
      - { option: 'enable', value: 'yes' }
      - { option: 'group', value: 'everybody' }
