---

- name: install workstation pkgs
  hosts: workstations
  become: true
  tasks:
  - name: install workstation pkgs
    pkgng:
      name: "{{ lookup('file', '../../templates/poudriere/poudriere.d/pkglist-dshs-workstation') }}"
