---

- name: install and activate opendkim
  hosts: mailserver
  become: true
  vars:
    dkim_key: dshs_mail_local_20260513
  tasks:
  - name: install opendkim
    pkgng:
      name: opendkim
  - name: add opendkim runsv directory
    ansible.builtin.file:
      path: '/etc/sv/{{ item }}'
      state: directory
      mode: '0755'
    loop:
      - milteropendkim_sign
      - milteropendkim_verify
  - name: add opendkim runsv file
    ansible.builtin.template:
      src: '../../templates/runit/{{ item }}_run'
      dest: '/etc/sv/{{ item }}/run'
      owner: root
      group: wheel
      mode: '0755'
    loop:
      - milteropendkim_sign
      - milteropendkim_verify
  - name: add dkim config files
    ansible.builtin.template:
      src: '../../templates/mail/{{ item }}'
      dest: '/usr/local/etc/mail/{{ item }}'
      owner: root
      group: wheel
      mode: '0644'
    loop:
      - opendkim-sign.conf
      - opendkim-verify.conf
  - name: configure opendkim
    ansible.builtin.lineinfile:
      dest: /usr/local/etc/mail/opendkim-sign.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^#? ?KeyFile\s', line: 'KeyFile	/var/db/dkim/{{ dkim_key }}.private' }
      - { regexp: '^#? ?Selector\s', line: 'Selector	{{ dkim_key }}' }
  - name: create domain keys dir
    ansible.builtin.file:
      path: /var/db/dkim
      state: directory
      owner: postfix
      group: postfix
      mode: 0700
  - name: check signing keys
    ansible.builtin.command:
      creates: '/var/db/dkim/{{ dkim_key }}.private'
      cmd: 'opendkim-genkey -b 1024 -d "{{ ansible_nodename.split(".")[1:]|join(".") }}" -D /var/db/dkim -s "{{ dkim_key }}" -v'
  - name: check signing key permissions
    ansible.builtin.file:
      path: "/var/db/dkim/{{ dkim_key }}.{{ item.ext }}"
      owner: postfix
      group: postfix
      mode: 0600
    loop:
      - { ext: 'private' }
      - { ext: 'txt' }
  - name: enable opendkim boot
    ansible.builtin.file:
      src: '/etc/sv/{{ item }}'
      dest: '/var/service/{{ item }}'
      state: link
    loop:
      - milteropendkim_sign
#      - milteropendkim_verify
