Pool {
  Name = Incremental
  Pool Type = Backup
  Recycle = yes                       # Bareos can automatically recycle Volumes
  AutoPrune = yes                     # Prune expired volumes
  # There are older volumes kept on DSHS-ATLAS and DSHS-BACKUP-J1
  Volume Retention = 10 days         # How long should the Incremenal Backups be kept?
  Maximum Volume Bytes = 10G          # Limit Volume size to something reasonable
  Maximum Volumes = 100               # Limit number of Volumes in Pool
  Label Format = "Incremental-"              # Volumes will be labeled "Full-<volume-id>"
}
