Pool {
  Name = Sneakernet-full
  Pool Type = Backup
  Recycle = yes                       # Bareos can automatically recycle Volumes
  AutoPrune = yes                     # Prune expired volumes
  Volume Retention = 15 days          # Doesn't delete straight away but only
                                      # keeps one set
  Maximum Volume Bytes = 10G          # Limit Volume size to something reasonable
  Maximum Volumes = 350               # Limit number of Volumes in Pool
  Storage = dshs-backup-j1
  Label Format = "Sneakernet-full-"
}
