---

- name: add items to loader.conf
  hosts: all
  become: true
  tasks:
  - name: force text mode in console
    ansible.builtin.lineinfile:
      path: /boot/loader.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    loop:
      - { regexp: '^hw.vga.textmode', line: 'hw.vga.textmode=1' }
