---

- name: enable UK console keymap and green the console
  hosts: all
  become: true
  tasks:
  - name: set keymap
    community.general.sysrc:
      name: keymap
      value: "uk.capsctrl.kbd"
  - name: set green console
    community.general.sysrc:
      name: allscreens_flags
      value: "green"
