---

- name: schedule weekly machine password reset
  hosts: all
  become: true
  tasks:
  - name: add periodic weekly directory
    ansible.builtin.file:
      path: /usr/local/etc/periodic/weekly
      state: directory
      mode: '0755'
  - name: add periodic script
    ansible.builtin.template:
      src: ../../templates/periodic/weekly/600.machine_password_reset
      dest: /usr/local/etc/periodic/weekly/600.machine_password_reset
      owner: root
      group: wheel
      mode: '0755'
  - name: enable periodic script
    ansible.builtin.lineinfile:
      path: /etc/periodic.conf
      regexp: ^weekly_machine_password_reset_enable
      line: weekly_machine_password_reset_enable=yes
      create: true
