---

- name: install and activate runit
  hosts: all
  become: true
  tasks:
  - name: install runit
    pkgng:
      name: runit
  - name: create runit service dir
    ansible.builtin.file:
      state: directory
      dest: /var/service
      owner: root
      group: wheel
      mode: '0755'
  - name: enable runit
    community.general.sysrc:
      name: runsvdir_enable
      value: yes
