---

- name: install and activate webfilter certificate
  hosts: dshs
  become: true
  tasks:
  - name: ensure certificates dir exists
    ansible.builtin.file:
      path: /usr/local/share/certs
      state: directory
  - name: install Netsweeper certificate
    ansible.builtin.template:
      src: ../../files/schoolsbroadband_cert/Talk_Straight.pem
      dest: /usr/local/share/certs/Talk_Straight.pem
      owner: root
      group: wheel
      mode: '0444'
    register: conf
  - name: rehash certificate store
    ansible.builtin.command:
      cmd: /usr/sbin/certctl rehash
    when: conf.changed
