---

- name: Configure hypervisors
  hosts: dshs-hv06.dshs.local
  become: true
  tasks:
  - name: install package
    pkgng:
      name: vm-bhyve
      state: present
  - name: enable vm rc.conf
    community.general.sysrc:
      name: 'vm_{{ item.var }}'
      value: "{{ item.val }}"
    loop:
      - { var: 'enable', val: 'yes' }
      - { var: 'dir', val: 'zfs:dumpster/bhyve' }
      - { var: 'list', val: 'status' }
      - { var: 'delay', val: '10' }
